[build]
	publish = "dest"
	command = "./n3sg.sh src dest '19 PDH Puszcza' https://puszcza.netlify.app"

[[plugins]]
package = "netlify-plugin-jekyll-cache"

[[redirects]]
 from = "/kuchnia/*"
 to = "https://zhr.niedzwiedzinski.cyou/kuchnia/:splat"
 status = 200
 force = true

[[redirects]]
 from = "/harcdzielnia/*"
 to = "https://zhr.niedzwiedzinski.cyou/harcdzielnia/:splat"
 status = 301
